### PR TITLE
AllSkyAI Module

### PR DESCRIPTION
**Pull request by TheCrowsNestAstro**
Classify the current sky condition based on machine learning. Let me know what you think would be the best place to store the downloaded files, atm they are stored within the module folder in a sub folder.

### CODE REVIEW

**Review by Alex-developer — COMMENTED** [review]
This looks REALLY cool. I am away until the 21st and dont have access to a system to test this on.

When I am back would you like to join the Allsky discord server and we can have a chat?

Just so that I can think about where to store/download the ai files - How big are they?

**Comment by TheCrowsNestAstro** [comment]
Cool! Send/email me a link and I'll join the server (could not find any official server)
Model file is approx. 65 Mb.

**Comment by Alex-developer** [comment]
> Cool! Send/email me a link and I'll join the server (could not find any official server) Model file is approx. 65 Mb.

Will do :-)

I found https://www.allskyai.com/ and if its the same speed as that then its looking really good.

Really appreciate the contribution.

One this that would be worth doing is to add a block at the beginning of the module and in the readme that explains who wrote it. Its only fair that people get credit otherwise it looks like I wrote them all !

Cheers

Alex

**Comment by TheCrowsNestAstro** [comment]
Hehe, ok good point :)
On my Pi4 it classifies in 0.3s. the debug log on the module page show 1.52s in total as it needs to load everything each time into memory, but I think it's acceptable.

/Chris

**Comment by Alex-developer** [comment]
> Hehe, ok good point :) On my Pi4 it classifies in 0.3s. the debug log on the module page show 1.52s in total as it needs to load everything each time into memory, but I think it's acceptable.
> 
> /Chris

0.3 is pretty damn good :-)

I have been thinking about having a separate process running that can take requests from a module, process them in parallel and then the next time the module runs it could pick them up - Probably as some form of REST interface

Lets chat when I am back

Cheers

Alex

**Comment by Alex-developer** [comment]
Chris

I am back now and will test this at the weekend. 

Where can I download the trained files from so I can test?

Invite link for discord https://discord.gg/KYKVd75q

**Review by Alex-developer — APPROVED** [review]

**Pull request merged**
