### PR TITLE
Added RoI to temperature

### PR DESCRIPTION
**Pull request by MichelMoriniaux**
Added a RoI field to limit the field of view taken into account for min/max/mean temperature reporting. this does not impact the final image ( maybe I'll add that in a future PR ).
With the widefield MLX90640 you can pick up the temperature of the housing that has a high temp compared to the sky so this allows to remove that and focus on a smaller portion of the sky.

some minor formatting changes due to pre-commit hooks that try to flake8
so the relevant code changes are:
lines 29: up of version
lines 36, 58 to 63: addition of roi param
lines  81 to 87: new version
lines 163 to 172: addition of method _sub_frame(frame, region)
lines 173, 185 to 186: modification of get_mean_temp()
llines 342, 346 to 350: modification of mlx90640()

all the rest are formatting changes, sorry for the mess.

### CODE REVIEW

**Comment by MichelMoriniaux** [comment]
This shows the impact to AS_MLX90640MAX_C when new code was activated around 18:11 
Screenshot 2024-04-19 183108

**Comment by Alex-developer** [comment]
@MichelMoriniaux Thanks for the mod, its a great addition.

Could you please make one change for me, in the changelog meta data you have accredited the change to me but it should have your details in it.

Once you have made the change I will merge it

Thanks

Alex

**Comment by MichelMoriniaux** [comment]
commit amended

**Comment by MichelMoriniaux** [comment]
commit amended,

**Pull request merged**
